version: "3.8"

networks:
  hive:
    name: hive
    ipam:
      config:
      - subnet: 13.13.13.0/24

services:
  aceitacao:
    image: node:15.10.0-alpine3.13
    working_dir: /ws/aceitacao
    volumes:
    - .:/ws
    entrypoint: /bin/sh -c 'yarn install && yarn dev; tail -f'
    networks:
    - hive

  hub:
    image: selenium/hub:3.141.59
    ports:
    - 4444
    networks:
    - hive

  chrome:
    image: selenium/node-chrome-debug:3.141.59
    ports:
    - 15900:5900
    env_file:
    - .selenium-node.env
    volumes:
    - .:/ws
    networks:
    - hive

  app:
    image: node:15.10.0-alpine3.13
    working_dir: /ws/app
    volumes:
    - .:/ws
    entrypoint: /bin/sh -c 'yarn install && yarn dev; tail -f'
    ports:
    - 17000:7000
    networks:
      hive:
        ipv4_address: 13.13.13.5
