version: "3.8"

services:
  aceitacao:
    image: node:15.10.0-alpine3.13
    working_dir: /ws/aceitacao
    volumes:
    - .:/ws
    entrypoint: /bin/sh -c 'yarn install && yarn dev; tail -f'

  hub:
    image: selenium/hub:3.141.59
    ports:
    - 4444

  chrome:
    image: selenium/node-chrome-debug:3.141.59
    ports:
    - 15900:5900
    env_file:
    - .selenium-node.env
    volumes:
    - .:/ws

  app:
    image: node:15.10.0-alpine3.13
    working_dir: /ws/app
    volumes:
    - .:/ws
    entrypoint: /bin/sh -c 'yarn install && yarn dev; tail -f'
    ports:
    - 17000:7000
